#!/bin/bash
# 测试加密数据传输

echo "=========================================="
echo "测试加密数据传输功能"
echo "=========================================="

echo ""
echo "步骤 1: 检查 Gateway 日志（查看加密数据接收）"
echo "=========================================="
echo "运行客户端后，查看最后 30 行日志..."
echo ""
echo "命令："
echo "kubectl logs -n vehicle-iot-gateway deployment/gateway --tail=30 | grep -E 'secure|加密|SM4|SM2'"

echo ""
echo "步骤 2: 运行客户端测试"
echo "=========================================="
echo "在项目根目录运行："
echo ""
echo "python client/vehicle_client.py \\"
echo "  --vehicle-id VIN_TEST_ENCRYPT \\"
echo "  --gateway-host 8.147.67.31 \\"
echo "  --gateway-port 32620 \\"
echo "  --mode once"

echo ""
echo "步骤 3: 验证数据是否正确保存"
echo "=========================================="
echo "检查数据库中是否有新数据..."
echo ""
kubectl exec -it deployment/postgres -n vehicle-iot-gateway -- \
  psql -U postgres -d vehicle_iot_gateway -c \
  "SELECT vehicle_id, timestamp, state, motion_speed FROM vehicle_data WHERE vehicle_id LIKE 'VIN_TEST%' ORDER BY timestamp DESC LIMIT 3;"

echo ""
echo "=========================================="
echo "测试完成！"
echo "=========================================="
echo ""
echo "预期结果："
echo "1. 客户端输出应显示："
echo "   - 正在使用 SM4 加密数据..."
echo "   - 加密后数据大小: XXX 字节"
echo "   - 签名长度: 64 字节"
echo "   - ✓ 加密数据发送成功"
echo "   - 签名验证: 通过"
echo ""
echo "2. Gateway 日志应显示："
echo "   - 接收到加密数据"
echo "   - SM2 签名验证通过"
echo "   - SM4 解密成功"
echo ""
echo "3. 数据库应有新记录"
