"""枚举类型定义"""

from enum import Enum


class ErrorCode(Enum):
    """错误码枚举"""
    INVALID_CERTIFICATE = "INVALID_CERTIFICATE"
    CERTIFICATE_EXPIRED = "CERTIFICATE_EXPIRED"
    CERTIFICATE_REVOKED = "CERTIFICATE_REVOKED"
    SIGNATURE_VERIFICATION_FAILED = "SIGNATURE_VERIFICATION_FAILED"
    CHALLENGE_RESPONSE_INVALID = "CHALLENGE_RESPONSE_INVALID"
    DECRYPTION_FAILED = "DECRYPTION_FAILED"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    REPLAY_ATTACK_DETECTED = "REPLAY_ATTACK_DETECTED"
    CA_SERVICE_UNAVAILABLE = "CA_SERVICE_UNAVAILABLE"
    CONCURRENT_SESSION_CONFLICT = "CONCURRENT_SESSION_CONFLICT"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"


class ValidationResult(Enum):
    """证书验证结果"""
    VALID = "VALID"
    INVALID = "INVALID"
    REVOKED = "REVOKED"


class SessionStatus(Enum):
    """会话状态"""
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    REVOKED = "REVOKED"


class EventType(Enum):
    """审计事件类型"""
    VEHICLE_CONNECT = "VEHICLE_CONNECT"
    VEHICLE_DISCONNECT = "VEHICLE_DISCONNECT"
    AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS"
    AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE"
    DATA_ENCRYPTED = "DATA_ENCRYPTED"
    DATA_DECRYPTED = "DATA_DECRYPTED"
    CERTIFICATE_ISSUED = "CERTIFICATE_ISSUED"
    CERTIFICATE_REVOKED = "CERTIFICATE_REVOKED"
    SIGNATURE_VERIFIED = "SIGNATURE_VERIFIED"
    SIGNATURE_FAILED = "SIGNATURE_FAILED"


class MessageType(Enum):
    """消息类型"""
    AUTH_REQUEST = "AUTH_REQUEST"
    AUTH_RESPONSE = "AUTH_RESPONSE"
    DATA_TRANSFER = "DATA_TRANSFER"
    RESPONSE = "RESPONSE"
    HEARTBEAT = "HEARTBEAT"
